config/routes.rb
Rails.application.routes.draw do

  root 'home#search'
  resources :pdf_spikes

end

app/models/pdf_spike.rb
require 'elasticsearch/model'
require 'pdf-reader'
class PdfSpike < ActiveRecord::Base
  after_create :parse_document
  mount_uploader :text, TextUploader
   include Elasticsearch::Model
   include Elasticsearch::Model::Callbacks

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'true' do
      indexes :title, analyzer: 'english'
      indexes :content, type: 'attachment'
    
    end
  end

  def parse_document
    reader = PDF::Reader.new(text.file.file)
    content_array = []
    reader.pages.each do |page|
      content_array << page.text
    end
    self.content = content_array.join(' ')
    self.save
  end

  def as_indexed_json(options = {})
    self.as_json(methods: [:attachment])
  end

end


PdfSpike.import

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def search
    if params[:search].present?
      @pdfs = PdfSpike.search params[:search]
    else
      @pdfs = []
    end
  end
end

app/controllers/pdf_spikes_controller.rb
class PdfSpikesController < ApplicationController
  before_action :set_pdfSpike, only: [:show, :edit, :update, :destroy]
  def index
    @pdfs = PdfSpike.all
  end
  def new
    @pdf= PdfSpike.new
  end
  def edit
  end
  def create
    @pdf= PdfSpike.new(pdf_spike_params)
    if @pdf.save
      redirect_to root_path
    else
      render :new
    end
  end
  def show
  end
  def update
    if @pdf.update(pdf_spike_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @pdf.destroy
    redirect_to pdf_spikes_path
  end
  private
  def set_pdfSpike
    @pdf = PdfSpike.find(params[:id])
  end
  def pdf_spike_params
    params.require(:pdf_spike).permit(:title,:detail,:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/views/home/search.html.erb
<%= form_for root_path, method: 'get' do %>
  <%=text_field_tag :search, params[:search], placeholder: "What are you looking for..?"%>
  <%= submit_tag 'Search', name: nil%> 
<% end %>
<% if params[:search].present?%>
<% if @pdfs.count > 0 %>
<table>
  <tr>
    <th>
      title
    </th>
    <th>
      Detail
    </th>
    <th>
      Download
    </th>
  </tr>  
  <tbody>
    
      <% @pdfs.each do |pdf|%>
      <tr>
      <td><%= pdf.title%></td>
      <td><%= pdf.detail%></td>
       <td><%= link_to 'View & Download', pdf.text.url%></td>
       </tr>
      <%end%>
    
  </tbody>

</table>
<% elsif @pdfs.count == 0%>
<h1>Results Not Found</h1>

<%end%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpikeSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pdf_spikes/_form.html.erb
<%= form_for(@pdf) do |f| %>
  <p>
    Title:
  </p>
  <p><%= f.text_field :title %></p>
  <p>
    Detail:
  </p>
  <p><%= f.text_field :detail %></p>
  <p>
    File:
  </p>
  <p><%= f.file_field :text %></p>

  <%= f.submit %>
<% end %>

app/views/pdf_spikes/index.html.erb
<% @pdfs.each do |pdf| %>
  <h1><%= pdf.title%></h1>
  <p><%= pdf.detail%></p>
  <%= link_to "Edit", edit_pdf_spike_path(pdf) %>
  <%= link_to "Show", pdf_spike_path(pdf) %>
  <%= link_to "Delete", pdf, method: :delete, data: {confirm: "Are you sure?" } %>
<% end %>

app/views/pdf_spikes/new.html.erb
<%= render 'form' %>

app/views/pdf_spikes/show.html.erb
<h1><%= @pdf.title%></h1>


<p><%= @pdf.detail%></p>

<%= link_to "Back", pdf_spikes_path %>